---
language: generic

sudo: required

services:
  - docker

install:
  - docker --version

env:
  - IMAGE="quay.io/nolith/ansible-dind" VERSION="ubuntu_14.04"
  - IMAGE="quay.io/nolith/ansible-dind" VERSION="ubuntu_12.04"

script:
  - ./tests/utils/run_test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
