---
language: python
python: "2.7"

sudo: required

services:
  - docker

# Install ansible
# addons:
#   apt:
#     packages:
#     - python-pip

install:
  # Check ansible version
  # - ansible --version
  # Check docker version
  - docker --version
  # Create ansible.cfg with correct roles_path
  #- printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - docker pull nolith/ansible-test:ubuntu_14.04
  - docker run -d --name ansible -v `pwd`:/data nolith/ansible-test:ubuntu_14.04
  - docker exec -it /bin/sh -c "ansible-playbook /data/tests/test.yml -i /data/tests/inventory --syntax-check"


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
